### ISSUE TITLE
Getting TypeError: (0 , ...) is not a function in example

### ISSUE THREAD

**Issue by jamwise** [Youpinadi/react-collider#10]
When I do npm start 

```
server.use((0, _reactCollider.server)(_srcRouting2['default']));
TypeError: (0 , _reactCollider.server) is not a function
```

**Comment by Xananax** [comment]
I'm not sure what's the policy on +1s here, but seeing as I've tried everything for hours without resolution, I'd like to get some help on this too.

**Comment by romainberger** [comment]
Hi,

If this is on the example from the repo, please try with the latest commit, it wasn't updated with the latest version of the lib. Thanks
